name: "multi_instance"
platform: "onnxruntime_onnx"
max_batch_size:16

input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [3, 224, 224] 
  }
]

output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [128] 
  }
]

instance_group [
  {
    count: 4
    kind: KIND_GPU 
  }
]

# Fix threads count to avoid throttling
parameters { key: "intra_op_thread_count" value: { string_value: "8" } }
parameters { key: "inter_op_thread_count" value: { string_value: "8" } }
parameters { key: "execution_mode" value: { string_value: "1" } }
