name: "default_model"
platform: "onnxruntime_onnx"

input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [3, 224, 224]  # Fixed dimensions for color channels and image size
  }
]

output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [1000]  # Fixed output size for ImageNet classification (1000 classes)
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU  # Deploy the model on a GPU
  }
]

# Fix threads count to avoid throttling
# parameters { key: "intra_op_thread_count" value: { string_value: "128" } }
# parameters { key: "inter_op_thread_count" value: { string_value: "128" } }
# parameters { key: "execution_mode" value: { string_value: "1" } }
